import os
import shutil

"""
USE CAREFULLY - This snippet will delete all the products generated by this pipeline. 

base_dir : Enter the directory which contains all the Swift observational data.
final_prods : Enter the directory which contains the final products from this pipeline.
"""

base_dir = ""

final_prods = ""


for item in os.listdir(base_dir):

    full_path = os.path.join(base_dir, item)

    # Keep only observation directories whose names are all digits
    if item.isdigit():
        continue

    if os.path.isdir(full_path):
        shutil.rmtree(full_path)
    else:
        os.remove(full_path)


obsids = os.listdir(base_dir)


for obs in obsids:

    survey_dir = os.path.join(base_dir, obs, "bat", "survey")

    if not os.path.isdir(survey_dir):
        continue

    for item in os.listdir(survey_dir):

        full_path = os.path.join(survey_dir, item)

        if os.path.isdir(full_path):
            shutil.rmtree(full_path)

        elif (
            (item.endswith(".dph") or item.endswith(".dph.gz"))
            and "erebin" not in item
        ):
            # Keep original DPH files
            pass

        else:
            os.remove(full_path)



if os.path.exists(final_prods):
    shutil.rmtree(final_prods)

os.makedirs(final_prods, exist_ok=True)